### ISSUE TITLE
rotation via keys not working in interacrive mode

### ISSUE THREAD

**Issue by m-reuter** [Deep-MI/WhipperSnapPy#16]
## Description
on Centos 7 in interactive mode, left right keys do not work for rotation. 

## Steps to Reproduce
start with -i flag and try to rotate object via keys, no reaction.

**Comment by AhmedFaisal95** [comment]
I was indeed able to replicate the issue in Ubuntu 20.04.

It should now be fixed in https://github.com/Deep-MI/WhipperSnapPy/pull/20 (tested on Ubuntu).

It was due to a subtle bug after adding the config window that lead to key presses not always being detected.
